### ISSUE TITLE
Can you provide me with a paper to read?

### ISSUE THREAD

**Issue by maomaoinszdx** [ZzZTripleZzZ/Digital-Network-Twins#1]
I'm interested in this research of yours, is there a paper or something you can share?

**Comment by ZzZTripleZzZ** [comment]
Thanks for your interest in this research! You can find the paper, "Mapping Wireless Networks into Digital Reality through Joint Vertical and Horizontal Learning," at this link: https://arxiv.org/pdf/2404.14497. This paper has been accepted by IFIP/IEEE Networking Conference 2024.

**Comment by maomaoinszdx** [comment]
&nbsp;&nbsp;Thank you very much for your reply, I will look into your paper and have a nice life!





------------------ Original ------------------
From: ZzZTripleZzZ ***@***.***&gt;
Date: Sun,May 12,2024 11:15 AM
To: ZzZTripleZzZ/Digital-Network-Twins ***@***.***&gt;
Cc: NicholasBiko ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ZzZTripleZzZ/Digital-Network-Twins] Can you provide me with apaper to read? (Issue #1)





 
Thanks for your interest in this research! You can find the paper, "Mapping Wireless Networks into Digital Reality through Joint Vertical and Horizontal Learning," at this link: https://arxiv.org/pdf/2404.14497. This paper has been accepted by IFIP/IEEE Networking Conference 2024.
